### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by marvin-bitterlich** [nate-strauser/meteor-publish-performant-counts#2]
```
I20170113-11:44:26.613(1)? Exception from sub numberOfJobs id xsxvwZCifT67F4Ni7 RangeError: Maximum call stack size exceeded
I20170113-11:44:26.613(1)?     at Object.EJSON.clone (packages\ejson.js:519:7)
I20170113-11:44:26.614(1)?     at packages\ejson.js:521:22
I20170113-11:44:26.614(1)?     at Function._.each._.forEach (packages\underscore.js:147:22)
I20170113-11:44:26.615(1)?     at Object.EJSON.clone (packages\ejson.js:520:5)
I20170113-11:44:26.615(1)?     at packages\ejson.js:521:22
I20170113-11:44:26.615(1)?     at Function._.each._.forEach (packages\underscore.js:147:22)
I20170113-11:44:26.615(1)?     at Object.EJSON.clone (packages\ejson.js:520:5)
I20170113-11:44:26.615(1)?     at packages\ejson.js:521:22
I20170113-11:44:26.616(1)?     at Function._.each._.forEach (packages\underscore.js:147:22)
I20170113-11:44:26.616(1)?     at Object.EJSON.clone (packages\ejson.js:520:5)
```

This pops up on the server when I try to subscribe to this collection:

```
Meteor.publish('numberOfJobs', function (filter: string) {
    let query: any = parseQuery(filter, this.userId);
    return new Counter('numberOfJobs', Jobs.find(query));
});
```

**Comment by nate-strauser** [comment]
are you sure it isnt your 'parseQuery' function?  the callstack doesnt
clearly indicate which line started the error.  seems like you are creating
the counter correctly.

**Comment by marvin-bitterlich** [comment]
My parsequery is just some sanitizing of the query. I got the same error when I just do a find without any query. (And I use the same parseQuery function for my normal publish and it works fine there)

**Comment by xonuzofa** [comment]
+1

 Exception from sub ordersWithOptionsCnt id wDR6SphAP8BsQDs5A { stack: 'RangeError: Maximum call stack size exceeded\n    at Object.EJSON.clone (packages/ejson.js:519:7)\n    at packages/ejson.js:521:22\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at Object.EJSON.clone (packages/ejson.js:520:5)\n    at packages/ejson.js:521:22\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at Object.EJSON.clone (packages/ejson.js:520:5)\n    at packages/ejson.js:521:22\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at Object.EJSON.clone (packages/ejson.js:520:5)',
